# fly.toml file generated for wild-sun-2963 on 2023-01-29T20:59:22-08:00

app = "wild-sun-2963"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  SKIP_SETCAP = "true"
  VAULT_LOCAL_CONFIG = "{\"disable_mlock\": true, \"storage\": {\"file\": {\"path\": \"/vault/file\"}}, \"listener\": [{\"tcp\": { \"address\": \"0.0.0.0:8200\", \"tls_disable\": true}}], \"ui\": true}"

[experimental]
  auto_rollback = true

[mounts]
  destination = "/var/lib/foundationdb/data/4500"
  source = "foundationdb_4500"

[[services]]
  http_checks = []
  internal_port = 8200
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
